name: Server Build and Unit Test

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./CritterServer
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./CritterServer
    - name: Test
      run: dotnet test --no-build --verbosity normal --filter Tests.UnitTests
      working-directory: ./CritterServer

